### ISSUE TITLE
Load FFmpeg and Opus for voice support on Heroku

### ISSUE THREAD

**Issue by justalemon** [justalemon/MEKAsystems#1]
As the title says, a way to automatically import/install/build the latest versions of FFmpeg and Opus to support audio without problems.

Currently the Heroku logs show:
```
2019-01-16T17:42:53.101714+00:00 app[worker.1]: Ignoring exception in on_message
2019-01-16T17:42:53.101950+00:00 app[worker.1]: Traceback (most recent call last):
2019-01-16T17:42:53.102020+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/discord/client.py", line 227, in _run_event
2019-01-16T17:42:53.102022+00:00 app[worker.1]:     await coro(*args, **kwargs)
2019-01-16T17:42:53.102026+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/discord/ext/commands/bot.py", line 936, in on_message
2019-01-16T17:42:53.102027+00:00 app[worker.1]:     await self.process_commands(message)
2019-01-16T17:42:53.102031+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/discord/ext/commands/bot.py", line 933, in process_commands
2019-01-16T17:42:53.102033+00:00 app[worker.1]:     await self.invoke(ctx)
2019-01-16T17:42:53.102036+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/discord/ext/commands/bot.py", line 898, in invoke
2019-01-16T17:42:53.102038+00:00 app[worker.1]:     await ctx.command.invoke(ctx)
2019-01-16T17:42:53.102041+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/discord/ext/commands/core.py", line 608, in invoke
2019-01-16T17:42:53.102043+00:00 app[worker.1]:     await self.prepare(ctx)
2019-01-16T17:42:53.102064+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/discord/ext/commands/core.py", line 574, in prepare
2019-01-16T17:42:53.102065+00:00 app[worker.1]:     await self.call_before_hooks(ctx)
2019-01-16T17:42:53.102067+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/discord/ext/commands/core.py", line 529, in call_before_hooks
2019-01-16T17:42:53.102069+00:00 app[worker.1]:     await self._before_invoke(cog, ctx)
2019-01-16T17:42:53.102075+00:00 app[worker.1]:   File "/app/ext/player.py", line 142, in ensure_playback
2019-01-16T17:42:53.102077+00:00 app[worker.1]:     await ctx.author.voice.channel.connect()
2019-01-16T17:42:53.102081+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/discord/abc.py", line 975, in connect
2019-01-16T17:42:53.102083+00:00 app[worker.1]:     voice = VoiceClient(state=state, timeout=timeout, channel=self)
2019-01-16T17:42:53.102109+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/discord/voice_client.py", line 110, in __init__
2019-01-16T17:42:53.102111+00:00 app[worker.1]:     self.encoder = opus.Encoder()
2019-01-16T17:42:53.102132+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/discord/opus.py", line 222, in __init__
2019-01-16T17:42:53.102134+00:00 app[worker.1]:     raise OpusNotLoaded()
2019-01-16T17:42:53.102162+00:00 app[worker.1]: discord.opus.OpusNotLoaded
2019-01-16T17:42:53.102371+00:00 app[worker.1]: Command by Lemon (236234499342598144): &play https://www.youtube.com/watch?v=_QqWO5kKFWc
```

**Comment by justalemon** [comment]
Also, I don't know if the buildpacks file works.
https://github.com/justalemon/MEKAsystems/blob/master/.buildpacks

**Comment by justalemon** [comment]
We are going to dump the voice support for the time being.
